/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void newMaskButton_click1(GButton source, GEvent event) { //_CODE_:newMaskButton:744727:
  println("newLayerButton - GButton >> GEvent." + event + " @ " + millis());
  makeNewMaskBox();
} //_CODE_:newMaskButton:744727:

public void widSlid_change1(GSlider source, GEvent event) { //_CODE_:widSlid:526036:
  ctrl.wd = source.getValueI();
} //_CODE_:widSlid:526036:

public void posSlid_change1(GSlider source, GEvent event) { //_CODE_:posSlid:726841:
  ctrl.x = source.getValueI();
} //_CODE_:posSlid:726841:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  newMaskButton = new GButton(this, 1041, 295, 100, 50);
  newMaskButton.setText("New Mask");
  newMaskButton.addEventHandler(this, "newMaskButton_click1");
  widSlid = new GSlider(this, 865, 488, 223, 40, 25.0);
  widSlid.setShowValue(true);
  widSlid.setShowLimits(true);
  widSlid.setLimits(50.0, 0.0, 420.0);
  widSlid.setShowTicks(true);
  widSlid.setNumberFormat(G4P.CYAN_SCHEME, 2);
  widSlid.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  widSlid.setOpaque(true);
  widSlid.addEventHandler(this, "widSlid_change1");
  posSlid = new GSlider(this, 862, 385, 224, 73, 30.0);
  posSlid.setLimits(120.0, 120.0, 540.0);
  posSlid.setNumberFormat(G4P.DECIMAL, 2);
  posSlid.setOpaque(false);
  posSlid.addEventHandler(this, "posSlid_change1");
  widLab = new GLabel(this, 759, 499, 80, 20);
  widLab.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  widLab.setText("Width");
  widLab.setOpaque(false);
  posLab = new GLabel(this, 733, 394, 120, 52);
  posLab.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  posLab.setText("Position");
  posLab.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton newMaskButton; 
GSlider widSlid; 
GSlider posSlid; 
GLabel widLab; 
GLabel posLab; 